### ISSUE TITLE
GFF3 output CDS records do not contain phase

### ISSUE THREAD

**Issue by diekhans** [agshumate/Liftoff#136]
https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md
"The phase is REQUIRED for all CDS features."

Mapping through the phase would allow the identification of frameshifts,
as well as allowing the validating parsers to parse the GFF3

**Comment by VibrantStarling** [comment]
We've just come across this issue as well. It looks like the Phase and Score are not carried over into the gff file or gtf file when they are made. Is there a reason for this?

![image](https://user-images.githubusercontent.com/47856505/225660439-80cd120d-7d39-441e-bf56-19824f425af0.png)

**Comment by salzberg** [comment]
We are working on this bug now - it should be an easy fix, sorry we didn't address it sooner.

**Comment by salzberg** [comment]
The bug should now be fixed in the latest github repo.

**Comment by diekhans** [comment]
thanks

**Comment by VibrantStarling** [comment]
The output gff still does not show phase information

(I am working through a conda installation on a remote server where I cannot install through the github repo because of permission issues)
